export const CONSULTAR_ORDEN_POR_PV = 'CONSULTAR_ORDEN_POR_PV';
export const LISTAR_ORDEN = 'LISTAR_ORDEN';
export const LISTAR_ORDEN_DETALLE = 'LISTAR_ORDEN_DETALLE';
export const REGISTRAR_ORDEN = 'REGISTRAR_ORDEN';
export const MODIFICAR_ORDEN = 'MODIFICAR_ORDEN';
export const REGISTRAR_ORDEN_DETALLE = 'REGISTRAR_ORDEN_DETALLE';
export const LISTAR_ARTICULO_DETALLE = 'LISTAR_ARTICULO_DETALLE';