export const CONSULTAR_ORDEN_POR_PV = 'CONSULTAR_ORDEN_POR_PV';
export const LISTAR_ORDEN_POR_PV = 'LISTAR_ORDEN_POR_PV';
export const REGISTRAR_ORDEN = 'REGISTRAR_ORDEN';
export const MODIFICAR_ORDEN = 'MODIFICAR_ORDEN';