export const USUARIO_LISTAR = 'USUARIO_LISTAR';
export const USUARIO_DETALLE = 'USUARIO_DETALLE';
export const USUARIO_REGISTRAR = 'USUARIO_REGISTRAR';
export const USUARIO_ACTUALIZAR = 'USUARIO_ACTUALIZAR';
export const USUARIO_ELIMINAR = 'USUARIO_ELIMINAR';